# conda environment description
#
# Use:
#
#   conda env create -f environment.yaml
#
# to create an environment in which you can run the ERDDAP_datasets notebook.

name: erddap-datasets

channels:
  - conda-forge
  - defaults

dependencies:
  - bottleneck
  - jupyterlab
  - lxml
  - netcdf4
  - nodejs
  - pip
  - python=3
  - xarray

# after creating the environment install extensions:
#
#  jupyter labextension install @jupyterlab/toc
#
#  jupyter labextension install @ryantam626/jupyterlab_code_formatter
#  conda install -c conda-forge jupyterlab_code_formatter
#  jupyter serverextension enable --py jupyterlab_code_formatter
