# conda environment description
#
# Use:
#
#   conda env create -f environment.yaml
#
# to create an environment in which you can run the ERDDAP_datasets notebook.

name: erddap-datasets

channels:
  - conda-forge
  - defaults

dependencies:
  - bottleneck
  - jupyterlab
  - jupyter_contrib_nbextensions
  - lxml
  - netcdf4
  - pip
  - python=3.6
  - xarray

  - pip:
      - yapf
