# conda environment description file for erddap-datasets testing environment
#
# Creates a conda environment in which the check_datasets_xml module can be run.
# Primarily intended for creation of a conda env for use in a GitHub Actions workflow.

name: erddap-datasets-test

channels:
  - conda-forge
  - nodefaults

dependencies:
  - lxml
  - pip
  - python=3.12
  - pyyaml
  - rich
  - structlog
