# conda environment description erddap-datasets dev environment
#
# Use:
#
#   mamba env create -f envs/environment-dev.yaml

name: erddap-datasets-dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  - bottleneck
  - docutils
  - jupyterlab
  - lxml
  - netcdf4
  - pip
  - python=3.12
  - pyyaml
  - rich
  - structlog
  - xarray

  # For coding style and repo QA
  - pre-commit
